### ISSUE TITLE
Demo website content

### ISSUE THREAD

**Issue by megvadulthangya** [pmoreno-rodriguez/grav-theme-editorial#10]
Hi! Is it possible somehow to get all of the content from the [demo website](http://editorial.juanvillen.es/)?

For example in joomla with quickstart 

You can install the whole CMS theme and a whole demo like [here](https://www.joomshaper.com/joomla-templates/helixultimate)... 

That way the user just need to change picture change the lorem ipsum thingy disable things and etc...
(im not good at creating website) patience:(

**Comment by pmoreno-rodriguez** [comment]
Hi @megvadulthangya 

In the next version of the theme I will include demo content. With demo content, when you install Grav, this gives you the option to install demo content.

**Comment by megvadulthangya** [comment]
Realy big thanks to you!

**Comment by pmoreno-rodriguez** [comment]
@megvadulthangya, the new Editorial theme version 1.0.5, already include do content.
