### ISSUE TITLE
grav-plugin-highlight does not work

### ISSUE THREAD

**Issue by roberteinsle** [pmoreno-rodriguez/grav-theme-editorial#11]
I love you theme but the grav-plugin-highlight does not work. Any help?

**Comment by pmoreno-rodriguez** [comment]
Hi @roberteinsle.

It seems that the plugin does not correctly inject the css file corresponding to each theme. However, the js file is present, and the line numbering works.
Does this plugin work in other Grav themes, no problem?

**Comment by pmoreno-rodriguez** [comment]
Hi @roberteinsle.

Try changing the [base.html.twig](https://github.com/pmoreno-rodriguez/grav-theme-editorial/blob/develop/templates/partials/base.html.twig)  from develop branch. 

Now, it works fine. See [Demo site](http://editorial.juanvillen.es/parent/child-one)

**Comment by pmoreno-rodriguez** [comment]
Fixed for new version. Currently in develop branch
