### ISSUE TITLE
Lightbox Gallery Plugin does not appear to work

### ISSUE THREAD

**Issue by Zardrastra** [pmoreno-rodriguez/grav-theme-editorial#12]
I have been attempting to embed light boxes in blogs using this theme.

When clicking on a light box the box appears to load under the bottom of the page aligned to the left with three blank photos under the image.

I have added the image as a Lightbox by using the following markup:

`![MountainBike](MountainBike.jpeg?lightbox=1024&cropResize=200,200)`

Specifically I am using the following plugin:
https://getgrav.org/premium/lightbox-gallery

But I have also tested this with featherlight:
https://github.com/getgrav/grav-plugin-featherlight

**Comment by pmoreno-rodriguez** [comment]
HI @Zardrastra.

The editorial theme seems to have some incompatibility with certain galleries js libraries.

I'll try to find a solution with the author of the original HTML5Up theme.

**Comment by pmoreno-rodriguez** [comment]
Hi @Zardrastra.

Try changing the [base.html.twig](https://github.com/pmoreno-rodriguez/grav-theme-editorial/blob/develop/templates/partials/base.html.twig) from develop branch with [Shortcode Gallery](https://github.com/sal0max/grav-plugin-shortcode-gallery-plusplus), which use the Glightbox JS library, the same one used by Lightbox Gallery Plugin.

I've been testing with this plugin and it works fine with Editorial Theme.

**Comment by pmoreno-rodriguez** [comment]
Can you visit the Editorial Theme [demo site](http://editorial.juanvillen.es/)?

I've uploaded two new pages, the first one with the Shortcode Gallery plugin and the other one with my Gallery (a new feature for the nex version)

It seems that work fine with the base.html.twig modification.

**Comment by Zardrastra** [comment]
Hello,

Yes both of these examples are what I was hoping to be able to do.
Both examples work fine. Your Gallery does look to be the better of the two
examples though, can't wait for your next version :)

**Comment by Zardrastra** [comment]
Can you clarify what edits I need to make to the base.html.twig file? I don't quite follow.

**Comment by pmoreno-rodriguez** [comment]
Look at the changes made to the file, via Github. [https://github.com/pmoreno-rodriguez/grav-theme-editorial/commit/48c7184189c35a5ee8ac36cfe0793bb0e4076f9e](https://github.com/pmoreno-rodriguez/grav-theme-editorial/commit/48c7184189c35a5ee8ac36cfe0793bb0e4076f9e)

 Don't pay too much attention to the comment I put for this review, it says "Update Changelog.md", it's wrong.

**Comment by Zardrastra** [comment]
Making those changes to the base.html.twig file resolved the light box issue, I tested this with the Lightbox Gallery plugin.

**Comment by pmoreno-rodriguez** [comment]
Ok. Thanks for your help testing the theme?. Can I close this issue?

**Comment by Zardrastra** [comment]
Yes of course, thank you once again!
