### ISSUE TITLE
change accent colour

### ISSUE THREAD

**Issue by jakedp** [pmoreno-rodriguez/grav-theme-editorial#15]
I found the accent colour in the main.css. Changed it and no avail. Then found have to compile the CSS with sassc (yuck, wtf?)... Now I found where the, to me, ugly red-pink accent colour is defined in the sass files. no color variable. So how do I change #f56a6a too #ff9933?, since it seems to get the color value from an imaginary place.  I went through every sass and css file!

**Comment by pmoreno-rodriguez** [comment]
@jakedp, I just changed the color #f56a6a to another color in main.css and everything works fine. Are you sure you are not using the compiled main (main.min.css is used if you choose Production mode in theme configuration)? If yes then you need to apply all changes in main.css and then compile it to main.min.css

Anyway, this is not a problem of the theme, rather a customization of it.

**Comment by jakedp** [comment]
I missed the var I wanted was in, surprise;  _vars at the bottom and missed it.
