### ISSUE TITLE
Sidebar contact info.

### ISSUE THREAD

**Issue by Zarius01** [pmoreno-rodriguez/grav-theme-editorial#17]
First off let me just say that I just started with Grav, and I tried about 10 themes, and I absolutely love this one that you've created.

I do have an issue though, as it seems I can't remove the sidebar contact info.  I would like to remove it entirely, but I also discovered that even just trying to remove the values defined eg; phone number (555) 555-5555 it keeps replacing it if I attempt to leave it blank, so I'm not sure if that is a bug or a feature.  Regardless is there an option in the theme I'm missing or is there another way to completely remove this block?

Thank you in advance.

-== Zarius

**Comment by pmoreno-rodriguez** [comment]
Hi @Zarius01 

Try these changes. You must overwrite these files (blueprints.yaml in the theme root folder and sidebar.html.twig in the /partials folder).
You will now be able to choose whether or not the contact section will be displayed.

In the next version of the theme, I will include these changes.

[blueprints.yaml.txt](https://github.com/pmoreno-rodriguez/grav-theme-editorial/files/11769299/blueprints.yaml.txt)
[sidebar.html.twig.txt](https://github.com/pmoreno-rodriguez/grav-theme-editorial/files/11769300/sidebar.html.twig.txt)

**Comment by Zarius01** [comment]
Hi @pmoreno-rodriguez 

Seems to have worked perfectly, I really appreciate you taking the time to make this modification.
