### ISSUE TITLE
Article visibility prior to publish date

### ISSUE THREAD

**Issue by Zarius01** [pmoreno-rodriguez/grav-theme-editorial#20]
Hi,

It appears that if you create an article and set a publish date in the future within the blog section it doesn't display until that defined date, however using the modular for recent posts, it displays the article immediately upon creation, even though it should not yet be visible.  I'm not sure if this is a bug or if this is by design, but it would be great if those articles weren't available until the scheduled publish date.

**Comment by pmoreno-rodriguez** [comment]
Hi @Zarius01 
Have you tried disabling caching option in advance tab in Recent Posts modular page?

**Comment by pmoreno-rodriguez** [comment]
HI, @Zarius01 
Could you try the new version of [recent-posts.html.twig](https://github.com/pmoreno-rodriguez/grav-theme-editorial/blob/develop/templates/modular/recent-posts.html.twig) template?

**Comment by Zarius01** [comment]
Hi Rodriguez,

Thank you again.  I tested your changes, and it seems to now be working as expected.  Articles on the recent-posts modular do not show up until the publish date is reached.

Really appreciate your effort!  I'm sure I'll use this theme for a very, very long time!
