### ISSUE TITLE
Lastest theme version

### ISSUE THREAD

**Issue by Zarius01** [pmoreno-rodriguez/grav-theme-editorial#21]
Hi Rodriquez,

I updated the theme to your newer version, however I noticed that the side bar contact information appeared again.  The function to disable it is present, but disabling it doesn't actually make it disappear.  I attempted to revert the sidebar.html.twig to the previous version you provided, but then it was showing featured posts in the sidebar which I had disabled.  Should I just put back the blueprints.yaml and sidebar.html.twig you provided previously, or are there other updates in those files as well and I should just wait until you've had a chance to take a look.

Thank you in advance.

**Comment by pmoreno-rodriguez** [comment]
Sorry @Zarius01 

In the latest version, I changed the 'defined' filter to the 'default' filter, but it doesn't work as expected.
I will upload a new version of template.

Thanks for your contribution.

**Comment by Zarius01** [comment]
Thank you Rodriquez.  Just updated the theme and all is working.
