### ISSUE TITLE
Sidebar issue on mobile

### ISSUE THREAD

**Issue by Zarius01** [pmoreno-rodriguez/grav-theme-editorial#22]
I really can't figure out if this is theme related or if it's tied to Grav itself, however since I've updated the theme to the latest version, I've noticed the the sidebar menu isn't updating custom links correctly and only on mobile.  Here is the scenario.

If I add a new page or new custom link, it shows correctly in PC based browsers and on mobile, however if I change an existing link it will update for PC based browsers by my mobile still shows the old link.  I've tried deleting the link all together and recreating and it somehow still pulls the old value.  I've cleared browser cache on the mobile device, I've cleared "all cache" in grav numerous times.  I've attempting changing cache settings, and disabling.  No matter what I do, the old links still persist on mobile.

Could this be something related to the sidebar for the theme, or do you believe it's Grav issue?  I initially assumed it was Grav, but then I wasn't so sure based on the fact that it only seems to be the custom links available from the theme that are problematic.

**Comment by pmoreno-rodriguez** [comment]
Hi @Zarius01 
I can't replicate your issue in my mobile. In admin panel I've created a new custom page  and then I've changed it later, but I didn't find any issue. Everything works well.

Maybe some error related with your browser cache or something else.

**Comment by Zarius01** [comment]
Ok thank you for checking.  It's very odd as I even had a user that has never been to the site test, and same scenario, from their PC they see the latest links, from their mobile device they see the old links.  I'm at a loss, but thank you for looking.

**Comment by pmoreno-rodriguez** [comment]
Hello @Zarius01. If you prefer, I could take a look at your test site, with a test user, to see if there are any errors or misconfigurations on your site.

**Comment by Zarius01** [comment]
Rodriguez, I really appreciate that.  Aside from the URL, do you need a temporary admin account to check it out I assume? Is there a way on github to message you privately if I'm going to pass the URL/credentials etc?  If not I can create an alias and post it here so you can email me, and I reply directly after which I can remove that alias account.

**Comment by pmoreno-rodriguez** [comment]
Hello @Zarius01. You can send me the credentials to the public email on GitHub. Is:
[birdydesign@tutanota.com](mailto:birdydesign@tutanota.com). Sorry, I thought this email was visible on the profile. Now yes.

**Comment by Zarius01** [comment]
Hi Rodriquez, I sent you an email with the details.  If you haven't had a chance to look no problem, but I did want to confirm if you received the email.

Thanks in advance.

Zar.

**Comment by pmoreno-rodriguez** [comment]
Hi @Zarius01. Is this problem already solved?.

**Comment by Zarius01** [comment]
Yes thank you Rodriquez it's working correctly now.
