### ISSUE TITLE
No input field in the contact page.

### ISSUE THREAD

**Issue by ventoux84** [pmoreno-rodriguez/grav-theme-editorial#23]
The "contact" page does not display the variables for email creation.
I can't see what I'm forgetting.

It's a page attached at the /home modular page. The title and the subtitle are displayed but no field of the form, like email, from, message ...
I have set the email plugin with "/usr/sbin/sendmail -t -i" and the email from and to.
All is up to date.

I thank whoever can put me on the right track

**Comment by pmoreno-rodriguez** [comment]
Hi @ventoux84. Check out to [https://learn.getgrav.org/16/forms/forms/example-form#close](https://learn.getgrav.org/16/forms/forms/example-form#close)

**Comment by pmoreno-rodriguez** [comment]
Hi @ventoux84.
Have you fixed this issue?.

**Comment by ventoux84** [comment]
Yes ! Thanks. As you writed I have read and apply the documentation.
I didn't think the template could exclude the form fields.

Gracias por su tema, que me va muy bien.

**Comment by ventoux84** [comment]
Gracias por su tema, que me va muy bien.

**Comment by pmoreno-rodriguez** [comment]
> Gracias por su tema, que me va muy bien.
> 
> I also modified languages.yaml to have these words in french.

You could make a French traslation and pull request in repository.
