### ISSUE TITLE
carateres coding in miniposts in left sidebar

### ISSUE THREAD

**Issue by ventoux84** [pmoreno-rodriguez/grav-theme-editorial#25]
Hello,
When i enable "Enable Featured posts in Sidebar ", miniposts text is displayed in html code.
For instance, "votre petit déjeuner" is `"votre petit d&eacute;jeuner".`

however, the text is correctly displayed in the blog item and in the modular page "recent post".

What can I change to get the right display ?
Theme version is 1.0.10.1

**Comment by pmoreno-rodriguez** [comment]
Hi @ventoux84 

Try changing line 22 in partials/featured-posts.html.twig for this:

`{{ p.summary|safe_truncate_html(25)|striptags|raw }}`

It is a bug. Thanks for your contribution.

**Comment by ventoux84** [comment]
Thanks, it works fine.
