### ISSUE TITLE
Suggestion: Make title optional

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#26]
Hi,

I added an "if" for title:
in /templates/modular/banner.html.twig
`{% if page.header.title %}<h1>{{ title|raw }}</h1>{% endif %}`
Because I use 2 banners, one with title, the other without ; then the folder name ("_folder") was printed as title

in /templates/modular/contact.html.twig
`{% if page.header.title %}<h2>{{ page.title }}</h2>{% endif %}`
Because I don't want title in contact page

Suggestion : integrate these changes upstream ?

**Comment by pmoreno-rodriguez** [comment]
Hi @Fazarel 
I will take into account your suggestions, and I will start working on them as soon as possible.

**Comment by Fazarel** [comment]
Thanks!

If the title is optional, then `{{ banner_image.cropZoom(736,512).html(title,title,'')|raw }}` in banner.html.twig is problematic. Personally I've removed `.html(title,title,'')`, in my case banner image is decorative...

**Comment by pmoreno-rodriguez** [comment]
I think it's better to define a title and have the option to display it or not. Images with the Alt or Tile parameter score better in Lighthouse website performance tests.

**Comment by pmoreno-rodriguez** [comment]
You had this: `{% if page.header.title %}<h1>{{ title|raw }}</h1>{% endif %}` to check if the title is null or empty or not, but it's better define a variable like `show_title` as a boolean and then check if that variable is true or false.
An example would be:
`{% if show_title == true %}<h1>{{ title|raw }}</h1>{% endif %}`
This way you can have a title defined on a page and show it whenever you want

**Comment by pmoreno-rodriguez** [comment]
Fixed in version 2.0.0
