### ISSUE TITLE
Accented and other characters in featured pages list

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#28]
in:
/templates/partials/featured-posts.html.twig

To solve printing of accented and other characters ("&" transformed into "&amp;")

Changes from:
`    <p>{{ p.summary|safe_truncate_html(25)|striptags }}</p>`

To:
`    <p>{{ p.summary|safe_truncate_html(25)|striptags|raw }}</p>`

**Comment by pmoreno-rodriguez** [comment]
Hi @Fazarel 

This issue is already solved in [Issue 25](https://github.com/pmoreno-rodriguez/grav-theme-editorial/issues/25)
