### ISSUE TITLE
Copyright text should have its own section in blueprints.yaml

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#29]
Copyright text is independent of contact information. Moreover, it doesn't make sense to be able to disable the section while the information entered in the copyright field will still be used.

Furthermore, in:
/templates/partials/footer.html.twig
I wouldn't put `&copy; {{ site.title }}.` to let total control over the text to be displayed from the theme settings.

**Comment by pmoreno-rodriguez** [comment]
@Fazarel I'm still thinking on this. For the moment, in new version 2, you will see some minor changes on copyright section.

**Comment by pmoreno-rodriguez** [comment]
and now I'm going to disconnect until the end of the month. 🙃

**Comment by pmoreno-rodriguez** [comment]
Fixed in 2.0.3 version
