### ISSUE TITLE
Content text in twig template

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#31]
In /templates/forms/fields/privacy/privacy.html.twig, line 33: 
`By using this form you agree with our <a href="{{base_url}}/privacy">{{field.label}}</a>`

This does not allow the first part of the sentence to be translated, either from user/pages/01.home/06._contact-us/contact.md or from another *.yaml file.

**Comment by pmoreno-rodriguez** [comment]
Hi.
I saw this issue the last week. I'll add it to my To-do list for this theme.

**Comment by pmoreno-rodriguez** [comment]
Fixed in version 2.0.0
