### ISSUE TITLE
Why don't you use custom.css?

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#35]
To apply a few modifications quickly and easily, why not allow custom.css to be used? As suggested in the documentation: https://learn.getgrav.org/17/themes/customization

Especially since the file exists `/assets/css/custom.css` and the comment in the first line invites you to use it...

For marginal modifications, it would be simpler than recompiling with SASS or modifying `/assets/css/misc.css`, which forces you to copy the entire content and loses the advantage of theme inheritance.

I suggest adding just one line to `/templates/partials/base.html.twig`
`{% do assets.addCss('theme://assets/css/custom.css', {'priority': 5}) %}`

**Comment by pmoreno-rodriguez** [comment]
I'm doing a deep review of the theme, improving some coding aspects and correcting some bugs (thanks to suggestions like yours), but at the moment I won't be able to make any more changes until the end of September since I'm on vacation.

**Comment by Fazarel** [comment]
Don't worry, I've understood that you're not immediately available. I just keep bumping up bugs and suggestions when I have time and before I forget, so they are tracked and you accept them or not when you have the time. Thanks again... and happy vacations!

**Comment by pmoreno-rodriguez** [comment]
Fixed in version 2.0.0
