### ISSUE TITLE
"more featured posts" button suggestion

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [pmoreno-rodriguez/grav-theme-editorial#38]
If I may make a suggestion in passing: I'm not sure it's relevant to list the "featured" tag, since the publications are already displayed above with a "more featured posts" button.
Unfortunately I don't see an option in the Taxonomy List plugin to easily exclude tags from the list...

_Originally posted by @Fazarel in https://github.com/pmoreno-rodriguez/grav-theme-editorial/issues/37#issuecomment-1825787981_

**Comment by pmoreno-rodriguez** [comment]
> Unfortunately I don't see an option in the Taxonomy List plugin to easily exclude tags from the list...

Could you test the recent 2.0.5 release to view the new changes in theme options to enable/disable sectións in sidebar?.

**Comment by Fazarel** [comment]
The ability to activate sidebar sections from theme options works with the new release.

But it doesn't address the issue raised in my post. The idea is to activate the "Popular tags" section and list all the tags (tag1, tag2, tag3...) except the tag "featured". This tag is irrelevant because it has no meaning in itself, but a technical use: to select the articles to be displayed in the "Featured Posts" section.

**Comment by pmoreno-rodriguez** [comment]
@Fazarel can you test with this change in your taxonomylist.html.twig file?

```
{% set featured_tag = theme_var('featured_tag') %}

{% for tax, value in taxlist[taxonomy] if tax != featured_tag %}
```

**Comment by pmoreno-rodriguez** [comment]
However, in my opinion, featured is one more tag, by which you can filter the blog articles, and you can have as many as you want, although with the theme configuration you can only put a maximum of five in the sidebar.
It's not clear to me that I should make a modification to this in the sense you indicate.

**Comment by pmoreno-rodriguez** [comment]
The featured articles section does not depend on any plugin, it searches within the blog collection, depending on whether the tag is 'featured_tag' (defined in the theme).
A user might want to have the 'Featured' section enabled without the 'Popular tags' section, or vice versa.
Let's imagine for a moment a blog with 500 posts, and that the user wants to highlight 20. Could they do it? Obviously, yes, although it can only show 5 in the sidebar (this option can be changed in the theme blueprint). If you click on the 'More featured posts' button you could obtain a filtered list of the articles marked as featured.
The opposite situation could also occur, where the user only wanted to have the popular tags section, without having the featured posts section activated.
Finally, I will review all the possible options more carefully in order to offer the user all the possible configuration alternatives.

**Comment by pmoreno-rodriguez** [comment]
Regarding translation suggestions, could you make a pull request?

**Comment by pmoreno-rodriguez** [comment]
[PR#33](https://github.com/pmoreno-rodriguez/grav-theme-editorial/commit/a69147bc60a813282aae38d9a025465615528bfa) already merged.
