### ISSUE TITLE
Incompatibility with Twig Extensions

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#39]
The latest version of the Twig Extensions plugin is incompatible with the theme.
After updating the plugin, an error message appears: 

> Twig\Error\RuntimeError thrown with message "An exception has been thrown during the rendering of a template ("Undefined variable $customDateFormat")."

Seems related to editorial/templates/partials/page-bits/date.html.twig
```
{% elseif config.plugins["twig-extensions"].enabled %}
    {% set datestamp = (page.header.publish_date) ? (page.header.publish_date|localizeddate('medium', 'none', lang)) : (page.date ? page.date|localizeddate('medium', 'none', lang) : page.modified|localizeddate('medium', 'none', lang)) %}
```

**Comment by pmoreno-rodriguez** [comment]
Thanks @bitstarr. I will close this issue.
