### ISSUE TITLE
Menu subitems

### ISSUE THREAD

**Issue by learningtime2025** [pmoreno-rodriguez/grav-theme-editorial#44]
Hello, i can make menu subitems jjust by adding directories.
but in that case i cant do to the top level from menu.
```
top1
top2
- sub1
- sub2
- -subsub1
- -subsub2
- sub3
top3
```
in that case i cant go to the content of the page sub2 from menu.

**Comment by pmoreno-rodriguez** [comment]
Hi @learningtime2025 
The editorial theme does not have implemented the function of accessing a parent page, with children, because if you add the 'opener' class it is not routable.
I'll investigate that possibility in later versions.

**Comment by learningtime2025** [comment]
Thank you. Can i also suggest some improvements?
for example in contacts in the sidebar - add fields for several phonenumbers with optional url with icons for popular messengers.
as example - whatsapp can have 2 versions open chat and make call.
 have some more ideas, let me know if you interested..

**Comment by learningtime2025** [comment]
As for the class 'opener'
didnt tried yet, but maybe checkbox for a page that will turn that option on/off will be enough. 
so users can switch the behavior for pages.

**Comment by pmoreno-rodriguez** [comment]
> Thank you. Can i also suggest some improvements?
> for example in contacts in the sidebar - add fields for several phonenumbers with optional url with icons for popular messengers.
> as example - whatsapp can have 2 versions open chat and make call.
> have some more ideas, let me know if you interested..

Hi. Can you make a pull request with your suggestions and improvements?. So, I will be able to revise them and merge in the develop branch.

**Comment by learningtime2025** [comment]
Reopen for copy/paste probably variants before test them:
+  whatsapp chat https://faq.whatsapp.com/5913398998672934/?locale=en_US&category=5245251
``
``
``

**Comment by pmoreno-rodriguez** [comment]
> As for the class 'opener' didnt tried yet, but maybe checkbox for a page that will turn that option on/off will be enough. so users can switch the behavior for pages.

Have you tried with 'dropdown enable' option in theme configuration?
