### ISSUE TITLE
incompatible with grav-plugin-shortcode-modal

### ISSUE THREAD

**Issue by learningtime2025** [pmoreno-rodriguez/grav-theme-editorial#46]
Seems like jquery error with
https://github.com/marshmn/grav-plugin-shortcode-modal

**Comment by pmoreno-rodriguez** [comment]
Well, can you elaborate more on what the problem is? You can attach a code or screenshot.

**Comment by pmoreno-rodriguez** [comment]
Hi @learningtime2025 
The shortcode-modal plugin is using version 0.9 of jquery.modal.min.js, which is not compatible with JQuery 3.6.4 (loaded with the latest versions of Grav), so you need to downgrade to version [0.91]( https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js) from the jquery.modal.min.js library
