### ISSUE TITLE
Missing "page" in blog-list-item.html.twig

### ISSUE THREAD

**Issue by Fazarel** [pmoreno-rodriguez/grav-theme-editorial#5]
In blog-list-item.html.twig, first line:
`{% set image = page.media[header.featured_image] ?: page.media.images|first %}`

I think it should be:
`{% set image = page.media[page.header.featured_image] ?: page.media.images|first %}`

otherwise it's always "first image" that is used, never featured_image

**Comment by pmoreno-rodriguez** [comment]
@Fazarel thanks for your correction. I will fix it for the next version.

**Comment by pmoreno-rodriguez** [comment]
Fixed in new version 1.0.4. Thanks
