### ISSUE TITLE
Images inserted into blog posts are not responsive

### ISSUE THREAD

**Issue by artecnico** [pmoreno-rodriguez/grav-theme-editorial#55]
The top banner image in blog posts it is totally responsive, but if you insert any image in the middle of a blog post it never resizes ( = it is NOT responsive).

You can try it by inserting a random image in any of your blog posts like this one:

https://editorial.pmdesign.dev/blog/post-two

Or check mine (latest Grav & Theme version, no custom code):

https://alejandrorodriguez.es/blog/

**Comment by pmoreno-rodriguez** [comment]
HI @artecnico 

By default, images included in the content of a Grav page are not responsive. To achieve this you need to use the classes that each theme provides for this, as you can see in the [Grav help](https://learn.getgrav.org/17/content/media#html).

The Editorial theme includes the `image` and `fit` classes that are used to make an image 100% of the width of the screen, this adjusting to any screen. This has a drawback on large screens, where the image may be too large.

You can customize your content on the page using the FlexRowShortcode from the Editorial theme, setting up multiple columns and inserting an image in each column, for example with the following code you would have 3 columns and one image per column, on small screens it would look like a single column:

```
[ed-flex-row class="gtr-50"]
[column class="col-4 col-12-medium"]
![image1](image1.jpg?classes=image,fit "Image 1")
[/column]
[column class="col-4 col-12-medium"]
![image2](image2.jpg?classes=image,fit "Image 2")
[/column]
[column class="col-4 col-12-medium"]
![image3](image3.jpg?classes=image,fit "Image 3")
[/column]
[/ed-flex-row]
```
It's all about digging into the theme's code, options, and CSS styles, as well as checking out Grav's help to configure the site to your liking.

**Comment by artecnico** [comment]
Thanks for the deep explanation!

Finally I managed to easily make images responsive (sort-of) just by adding this string when inserting them:

?derivatives=[360,420,720,1200]

Example: for the image ![089_crop2](089_crop2.jpg "089_crop2") it will be:

![089_crop2](089_crop2.jpg?derivatives=[360,420,720,1200] "089_crop2")

I write it here just in case someone likes this solution. The only downside of this method is that it breaks the top-left menu enabling/disabling
