### ISSUE TITLE
Gallery images' description not HTML encoded

### ISSUE THREAD

**Issue by artecnico** [pmoreno-rodriguez/grav-theme-editorial#56]
If you put " (or any other special char) inside any image's description (in a Gallery), it breaks the code.

Example: https://alejandrorodriguez.es/blog/galeria (second picture "Inglaterra 2023") -> The image description shows correctly when hovering, but gets cut when opening the picture.

I think it's similar to this other issue (thanks for fixing it!): https://github.com/pmoreno-rodriguez/grav-theme-editorial/issues/51

**Comment by pmoreno-rodriguez** [comment]
Hi @artecnico 
Thanks for the report. There is indeed a small error in the gallery template code, which I will fix in the next version (as soon as I can).
For now you can change the following code on line 46 (or close):
```
<a href="{{item_image.url}}" class="glightbox" data-height="{{page.header.height}}" data-width="{{page.header.width}}" data-title="{{item_title}}" data-description="{{item_desc|e('html_attr')|raw}}" data-desc-position="{{item.descPosition}}" data-zoomable="{{page.header.zoomable}}" data-draggable="{{page.header.draggable}}" data-type="image">
```
The only change to make on that line is to add the filter `|e('html_attr')` to the image description. I've tested it and it works fine now.

**Comment by pmoreno-rodriguez** [comment]
Fixed in last version
