### ISSUE TITLE
The "Grav" text is always added to the theme slogan.

### ISSUE THREAD

**Issue by iGyver** [pmoreno-rodriguez/grav-theme-editorial#62]
I have installed the newest theme version direct within Grav. 

If I leave the team slogan blank, the word "Grav" still appears in front of my theme slogan. I can't find where to remove it.

![Screenshot 2024-12-21 165401](https://github.com/user-attachments/assets/3235a558-f1e5-4e8b-922d-edfd82fc3c32)

**Comment by pmoreno-rodriguez** [comment]
Hi @iGyver.
The text "Grav" is the site name in the Configuration menu. You need to change it there or leave it blank.

![grav_configuration](https://github.com/user-attachments/assets/951f6159-8c43-4bcf-ae2d-1c9e3d7e167d)

**Comment by iGyver** [comment]
Done. That was quick. Thank you. Have a nice day!

**Comment by iGyver** [comment]
Solved
